#!/bin/bash

function _process {
	olog Clearing containers…
	dockercels | grep -v 'CONTAINER ID' | grep -v 'exist' | tr -s [:space:] | rev | cut -d' ' -f1 | rev | tr '\n' ' ' | ofor dockerstoprm this || errexit "$0 Unable" || exit 1
}

_process

